apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  infra: {}
  workloads:
    nodePlacement:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/baremetal
