apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  channel: {{ .Values.subscriptionChannel }}
  installPlanApproval: {{ .Values.subscriptionApproval }}
  name: kubevirt-hyperconverged
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    selector:
      matchLabels:
        name: hyperconverged-cluster-operator
    env:
    - name: KVM_EMULATION
      value: {{ .Values.kvmEmulationEnabled | toString | squote }}
