apiVersion: v1
kind: Namespace
metadata:
#  labels:
#    openshift.io/cluster-monitoring: "true"
  name: {{ .Values.namesapce }}
  annotations: 
   "helm.sh/hook": pre-install
   "helm.sh/hook-weight": "-5"
