apiVersion: velero.io/v1
kind: Backup
metadata:
  generateName: test-vm-
  namespace: openshift-adp
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  includedNamespaces:
  - test-vm
  snapshotVolumes: true
  storageLocation: velero-sample-1
  ttl: 720h0m0s
